version: "3.8"

services:

  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 3000:3000

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api: 
    depends_on: 
      - db

    build: ./backend
    ports: 
      - 8000:8000

    environment: 
      MONGO_URI: mongodb://db/todos
      PORT: 8000
    
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        
        - path: ./backend
          target: /app
          action: sync

  # define the db service
  db:
    image: mongo:latest

    ports:
      - 27017:27017
    volumes:
      - todos:/data/db

volumes:
  todos: